language: perl
perl:
  # - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
before_install:
  - cpanm -n git://github.com/kan/coveralls-perl.git
script: ./Build testcover
after_success:
  - cover -report coveralls
